config:
  project_repos:
    deepaas:
      repo: https://github.com/indigo-dc/DEEPaaS.git

sqa-criteria:
  qc-style:
    repos:
      deepaas:
        container: deepaas-testing
        tox:
          testenv: pep8
  qc-coverage:
    repos:
      deepaas:
        container: deepaas
        tox:
          testenv: 
            - cover
            - cobertura
  qc-security:
    repos:
      deepaas:
        container: deepaas
        tox:
          testenv: bandit
