config:
  project_repos:
    deepaas:
      repo: https://github.com/indigo-dc/DEEPaaS.git

sqa_criteria:
  qc_style:
    repos:
      deepaas:
        container: DEEPaaS-testing
        tox:
          tox_file: /deepaas-testing/tox.ini
          testenv:
            - pep8
  qc_coverage:
    repos:
      deepaas:
        container: DEEPaaS-testing
        tox:
          tox_file: /deepaas-testing/tox.ini
          testenv: 
            - cover
            - cobertura
  qc_security:
    repos:
      deepaas:
        container: DEEPaaS-testing
        tox:
          tox_file: /deepaas-testing/tox.ini
          testenv:
            - bandit
