version: "3"

services:
  DEEPaaS:
    build:
      context: .
      dockerfile: Dockerfile
    image: "samuelbernardolip/deepaas:initial-sqa"
    container_name: "deepaas"
    hostname: "deepaas"
    volumes:
     - type: bind
       source: DEEPaaS
       target: /home/DEEPaaS

volumes:
  jenkins-pipeline-library: ./DEEPaaS

